name: newproject
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib
  - pytorch
  - jupyter
  - notebook
  - ipykernel
  - ipywidgets
  - ipympl
  - pip
  - pip:
    - tqdm